# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='realName',
            field=models.CharField(default='sdfg', max_length=20),
            preserve_default=False,
        ),
    ]
