# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0002_feedback_realname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='realName',
            field=models.CharField(max_length=100),
        ),
    ]
