# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0003_auto_20160819_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=7, unique=True)),
                ('path', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
