# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='index',
            field=models.CharField(max_length=7),
        ),
    ]
