# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 03:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0005_auto_20160822_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sess_id',
            field=models.CharField(default=datetime.datetime(2016, 8, 22, 3, 54, 58, 633635, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
