# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0006_user_sess_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='path',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='sess_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
