# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0007_auto_20160822_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sess_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
