# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculater', '0008_auto_20160822_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
