# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0003_auto_20160912_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='credit',
            field=models.CharField(default=2, max_length=4),
            preserve_default=False,
        ),
    ]
