# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0004_module_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='overallGPA',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=6),
            preserve_default=False,
        ),
    ]
