# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0005_auto_20161026_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cookie',
            field=models.CharField(max_length=100),
        ),
    ]
