# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-30 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0006_auto_20161031_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.CharField(max_length=100),
        ),
    ]
