# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-30 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0007_auto_20170730_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
    ]
