# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-06 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0011_auto_20170805_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.CharField(default='UNKNOWN', max_length=8),
        ),
    ]
