# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-17 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0012_auto_20170806_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_msg',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
