# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-17 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0014_profile_is_msg_showed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admin_msg',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
