# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-31 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0017_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='isNonGPA',
            field=models.BooleanField(default=False),
        ),
    ]
