# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0018_module_isnongpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
